#!/bin/bash
showflags=0
target=$1
if [ -z "$target" ]; then
  printf "what virt machine? "
  showflags=1
  read target
fi

sharedir=$2
if [ ! -d "$sharedir" ]; then
  printf "source directory for ISO filesystem? "
  showflags=1
  read sharedir
fi

if [ ! -d "$sharedir" ]; then
  echo "fatal: $sharedir" is not a directory
  exit 222
fi

if [ 1 = $showflags ]; then
  echo
  echo
  echo "Next time, run: $(basename $0) $target $sharedir"
  echo
  echo "Press ENTER to continue, or ctrl+c to bail out"
  read PRESS_ENTER
fi


cdrom=${cdrom-$(tempfile -p cdrom -s .iso)}

echo
echo "##### Creating ISO filesystem... ######"
mkisofs -J -r -o $cdrom $sharedir

echo
echo "##### Mounting in VM... #####"
virsh -c qemu:///system change-media $target hdb $cdrom
